### ISSUE TITLE
Notejot is Missing in Apps Section

### ISSUE THREAD

**Issue by lainsce** [flathub/flathub.org#36]
Sorry for raising an issue for this, but it seems my app Notejot, which has a flatpak repo, and distributed by flathub already, is missing in the website apps grid.

**Comment by TingPing** [comment]
This is almost always a problem with your appstream file though at a glance I didn't see anything obvious.

 It is best to track this issue over at https://github.com/flathub/com.github.lainsce.notejot because this repository is largely for the web developers who have nothing to do with that generated file.
